name:

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - terraform/**

env:
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: "bml"
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash 
        # We keep Terraform files in the terraform directory 
        working-directory: ./terraform 

    steps:
      - name: Checkout the repository 
        uses: action/checkout@v3

      - name: Setup Terraform with specified version on the runner 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0 

      - name: terraform init 
        id: init 
        run: terraform init 

      - name: terraform format 
        id: fmt 
        run: terraform fmt -check

      - name: terraform validate 
        id: validate 
        run: terraform validate 

      - name: terraform plan 
        id: plan
        if: github.event_name == 'pull request'
        run: terraform plan -no-color -input=false 
        continue-on-error: true 

      - name: terraform plan status 
        if: steps.if.outcome == 'failure'
        run: exit 1 

      - name: terraform apply 
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

